<x-app-layout>
    <x-slot name="header"><h2 class="text-xl font-semibold leading-tight text-gray-800">{{ __('Dashboard') }}</h2></x-slot>
    <div class="py-12"><div class="mx-auto max-w-7xl sm:px-6 lg:px-8"><div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
        <div class="rounded-xl bg-emerald-700 p-6 text-white shadow"><p>{{ __('Enrolled students') }}</p><p class="mt-2 text-3xl font-bold">{{ $studentCount }}</p></div>
        <div class="rounded-xl bg-white p-6 shadow"><p class="text-gray-500">{{ __('Teachers') }}</p><p class="mt-2 text-3xl font-bold text-emerald-700">{{ $teacherCount }}</p></div>
        @can('roles.manage')<div class="rounded-xl bg-white p-6 shadow"><p class="text-gray-500">{{ __('Administrative staff') }}</p><p class="mt-2 text-3xl font-bold text-emerald-700">{{ $staffCount }}</p></div>@endcan
        @can('payments.view')<div class="rounded-xl bg-red-50 p-6 shadow ring-1 ring-red-100"><p class="text-red-700">{{ __('Overdue school fees') }}</p><p class="mt-2 text-3xl font-bold text-red-700">{{ number_format($overdueInvoices, 0, ',', ' ') }} Ar</p></div><div class="rounded-xl bg-emerald-50 p-6 shadow ring-1 ring-emerald-100"><p class="text-emerald-700">{{ __('Amount collected') }}</p><p class="mt-2 text-3xl font-bold text-emerald-700">{{ number_format($collectedAmount, 0, ',', ' ') }} Ar</p></div>@endcan
        @can('expenses.view')<div class="rounded-xl bg-orange-50 p-6 shadow ring-1 ring-orange-100"><p class="text-orange-700">{{ __('Expenses') }}</p><p class="mt-2 text-3xl font-bold text-orange-700">{{ number_format($totalExpenses, 0, ',', ' ') }} Ar</p></div>@endcan
    </div>@can('students.create')<div class="mt-6 rounded-xl bg-white p-6 shadow"><div class="flex items-center justify-between"><h2 class="text-lg font-semibold">{{ __('Quick actions') }}</h2>@can('roles.manage')<button type="button" title="{{ __('Trash') }}" onclick="openTrashModal()" class="inline-flex h-10 w-10 items-center justify-center rounded-full bg-slate-800 text-lg text-white">🗑</button>@endcan</div><a class="mt-4 inline-block rounded-lg bg-emerald-700 px-4 py-2 text-white" href="{{ route('students.create') }}">{{ __('Enroll a student') }}</a>@can('login_history.view')<a class="ml-3 mt-4 inline-block rounded-lg bg-gray-800 px-4 py-2 text-white" href="{{ route('admin.history.index') }}">{{ __('History') }}</a>@endcan</div>@endcan
    </div></div>
    @can('roles.manage')@php($trashItems = \App\Models\DeletedItem::with('deletedBy')->latest('deleted_at')->take(30)->get())<div id="trash-modal" class="fixed inset-0 z-[90] hidden items-center justify-center bg-black/40 p-4"><div class="flex max-h-[85vh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><div class="flex items-center justify-between border-b border-slate-100 px-6 py-4"><div><h2 class="font-semibold text-slate-900">{{ __('Trash') }}</h2><p class="text-sm text-slate-500">{{ __('Deleted items can be restored here.') }}</p></div><button type="button" onclick="closeTrashModal()" class="rounded-lg px-3 py-2 text-slate-500 hover:bg-slate-100">{{ __('Close') }}</button></div><div class="overflow-y-auto p-6"><div class="space-y-3">@forelse($trashItems as $item)<div class="flex flex-col gap-3 rounded-xl border border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-medium text-slate-800">{{ $item->localizedLabel() }}</p><p class="mt-1 text-xs text-slate-500">{{ $item->deletedBy?->localizedFunctionLabel() ?? __('System') }} · {{ $item->deleted_at->format('d/m/Y H:i') }}</p></div><div class="flex gap-2"><form method="POST" action="{{ route('admin.trash.restore', $item) }}">@csrf<button class="rounded-lg bg-emerald-700 px-3 py-2 text-sm text-white">{{ __('Restore') }}</button></form><a href="{{ route('admin.trash.index') }}" class="rounded-lg border border-red-200 px-3 py-2 text-sm text-red-700">{{ __('Delete permanently') }}</a></div></div>@empty<p class="py-10 text-center text-sm text-slate-500">{{ __('Trash is empty.') }}</p>@endforelse</div></div><div class="border-t border-slate-100 px-6 py-4 text-right"><a href="{{ route('admin.trash.index') }}" class="mr-3 text-sm text-emerald-700">{{ __('View all') }}</a><button type="button" onclick="closeTrashModal()" class="rounded-lg bg-slate-800 px-4 py-2 text-sm text-white">{{ __('Close') }}</button></div></div></div><script>function openTrashModal(){document.getElementById('trash-modal').classList.remove('hidden');document.getElementById('trash-modal').classList.add('flex')}function closeTrashModal(){document.getElementById('trash-modal').classList.add('hidden');document.getElementById('trash-modal').classList.remove('flex')}</script>@endcan
    @can('roles.manage')<script>document.addEventListener('DOMContentLoaded',()=>document.querySelector('#trash-modal .border-t button[onclick="closeTrashModal()"]').remove());</script>@endcan
    @can('roles.manage')@php($trashCount = \App\Models\DeletedItem::count())<script>document.addEventListener('DOMContentLoaded',()=>{const button=document.querySelector('button[onclick="openTrashModal()"]');if(!button)return;button.classList.add('relative');const badge=document.createElement('span');badge.id='trash-count-badge';badge.textContent='{{ $trashCount > 99 ? '99+' : $trashCount }}';badge.style.cssText='position:absolute;top:-7px;right:-7px;min-width:20px;height:20px;padding:0 4px;border-radius:999px;background:#dc2626;color:#fff;font-size:11px;font-weight:700;display:{{ $trashCount ? 'flex' : 'none' }};align-items:center;justify-content:center;';button.appendChild(badge);window.updateTrashBadge=increment=>{const current=Number(button.dataset.trashCount||{{ $trashCount }});const next=current+Number(increment);button.dataset.trashCount=next;badge.textContent=next>99?'99+':next;badge.style.display=next?'flex':'none'}});</script>@endcan
    @can('roles.manage')<div id="trash-empty-modal" class="fixed inset-0 z-[110] hidden items-center justify-center bg-black/40 p-4"><form method="POST" action="{{ route('admin.trash.destroy-all') }}" class="w-full max-w-sm rounded-2xl bg-white p-6 text-center shadow-2xl">@csrf @method('DELETE')<h2 class="text-lg font-semibold text-slate-900">{{ __('Empty trash permanently') }}</h2><p class="mt-2 text-sm text-slate-600">{{ __('This action cannot be undone. Enter your administrator password.') }}</p><input type="password" name="admin_password" required autocomplete="current-password" class="mt-4 w-full rounded-lg border-slate-300 text-left"><div class="mt-6 flex justify-center gap-3"><button type="button" onclick="closeEmptyTrashModal()" class="rounded-lg border border-slate-300 px-4 py-2">{{ __('Cancel') }}</button><button class="rounded-lg bg-red-600 px-4 py-2 text-white">{{ __('Delete all permanently') }}</button></div></form></div><script>function openEmptyTrashModal(){const modal=document.getElementById('trash-empty-modal');modal.classList.remove('hidden');modal.classList.add('flex')}function closeEmptyTrashModal(){const modal=document.getElementById('trash-empty-modal');modal.classList.add('hidden');modal.classList.remove('flex')}document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('#trash-modal a[href$="/admin/trash"]').forEach(link=>link.remove());const footer=document.querySelector('#trash-modal .border-t');if(footer){const button=document.createElement('button');button.type='button';button.textContent='{{ __('Delete all permanently') }}';button.className='rounded-lg bg-red-600 px-4 py-2 text-sm text-white';button.onclick=openEmptyTrashModal;footer.prepend(button)}});</script>@endcan
    @can('roles.manage')<script>document.addEventListener('DOMContentLoaded',()=>{const modal=document.getElementById('trash-empty-modal');const open=()=>{modal.style.cssText='position:fixed;inset:0;z-index:10000;display:flex;align-items:center;justify-content:center;';modal.classList.remove('hidden');modal.classList.add('flex')};window.openEmptyTrashModal=open;const button=[...document.querySelectorAll('#trash-modal .border-t button')].find(item=>item.textContent.trim()==='{{ __('Delete all permanently') }}');if(button)button.onclick=open;});</script>@endcan
    @can('roles.manage')<script>window.closeEmptyTrashModal=()=>{const modal=document.getElementById('trash-empty-modal');modal.style.display='none';modal.classList.add('hidden');modal.classList.remove('flex')};</script>@endcan
</x-app-layout>
