<x-app-layout>
    <x-slot name="header"><h2 class="font-semibold text-xl">{{ __('Class students') }}</h2></x-slot>
    <div class="mx-auto max-w-5xl py-8 sm:px-6 lg:px-8"><div class="rounded-xl bg-white p-6 shadow">
        <div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="text-2xl font-bold">{{ $schoolClass->name }}</h3><p class="text-gray-500">{{ $schoolClass->academicYear->name }} · {{ $schoolClass->duration_months }} {{ __('months') }}</p></div><div class="flex gap-3"><a href="{{ route('classes.index') }}" class="rounded border px-4 py-2">{{ __('Back') }}</a>@if(auth()->user()->hasRole('Admin'))<form id="delete-class-form" method="POST" action="{{ route('classes.destroy', $schoolClass) }}">@csrf @method('DELETE')<button type="button" onclick="openClassSecurityModal(this.closest('form'), '{{ __('Delete class') }}', true)" class="rounded bg-red-700 px-4 py-2 text-white">{{ __('Delete class') }}</button></form>@endif</div></div>
        <p class="mt-5 text-sm text-gray-600">{{ __('Registered students') }}: <strong>{{ $schoolClass->enrollments->count() }}</strong></p>
        <form id="transfer-students-form" method="POST" action="{{ route('classes.transfer-students', $schoolClass) }}">@csrf @method('PATCH')
            <div class="mt-4 overflow-x-auto"><table class="w-full text-left"><thead><tr class="border-b"><th class="p-2"><input type="checkbox" onclick="document.querySelectorAll('.student-transfer').forEach(box=>box.checked=this.checked)"></th><th class="p-2">{{ __('Student number') }}</th><th class="p-2">{{ __('Student') }}</th><th class="p-2">{{ __('Enrolled on') }}</th><th class="p-2">{{ __('Action') }}</th></tr></thead><tbody>@forelse($schoolClass->enrollments as $enrollment)<tr class="border-b"><td class="p-2"><input class="student-transfer" type="checkbox" name="student_ids[]" value="{{ $enrollment->student_id }}"></td><td class="p-2">{{ $enrollment->student->student_number }}</td><td class="p-2">{{ $enrollment->student->last_name }} {{ $enrollment->student->first_name }}</td><td class="p-2">{{ optional($enrollment->enrolled_on)->format('d/m/Y') }}</td><td class="p-2"><a href="{{ route('students.show', $enrollment->student) }}" class="text-emerald-700">{{ __('View') }}</a></td></tr>@empty<tr><td colspan="5" class="p-4">{{ __('No student.') }}</td></tr>@endforelse</tbody></table></div>
            @if($schoolClass->enrollments->isNotEmpty() && $targetClasses->isNotEmpty())<div class="mt-5 flex flex-wrap items-end justify-between gap-3 border-t pt-4"><label class="block">{{ __('Transfer selected students to') }}<select name="target_class_id" required class="mt-1 block min-w-56 rounded border-gray-300"><option value="">—</option>@foreach($targetClasses as $target)<option value="{{ $target->id }}">{{ $target->name }} — {{ $target->academicYear->name }}</option>@endforeach</select></label><button type="button" onclick="openTransferModal()" class="rounded bg-emerald-700 px-4 py-2 text-white">{{ __('Transfer selected students') }}</button></div>@endif
        </form>
    </div></div>
    <div id="class-security-modal" class="fixed inset-0 z-50 hidden items-center justify-center bg-black/40 p-4"><div class="w-full max-w-sm rounded-xl bg-white p-6 shadow-xl"><h3 id="class-security-title" class="text-lg font-semibold"></h3><p id="class-security-message" class="mt-2 text-sm text-gray-600"></p><label class="mt-4 block text-sm">{{ __('Your password') }}<input id="class-security-password" type="password" class="mt-1 w-full rounded border-gray-300"></label><div class="mt-5 flex justify-end gap-3"><button type="button" onclick="closeClassSecurityModal()" class="rounded px-4 py-2">{{ __('Cancel') }}</button><button type="button" onclick="submitClassSecurityModal()" class="rounded bg-emerald-700 px-4 py-2 text-white">{{ __('Confirm') }}</button></div></div></div>
    <script>let sensitiveClassForm=null;function openClassSecurityModal(form,title,isDelete){sensitiveClassForm=form;document.getElementById('class-security-title').textContent=title;document.getElementById('class-security-message').textContent=isDelete?'{{ __('This permanently deletes the class and all currently enrolled students. This action cannot be undone.') }}':'{{ __('Confirm this action with your password.') }}';document.getElementById('class-security-modal').classList.remove('hidden');document.getElementById('class-security-modal').classList.add('flex');document.getElementById('class-security-password').focus()}function openTransferModal(){const form=document.getElementById('transfer-students-form');if(!form.querySelector('.student-transfer:checked')){alert('{{ __('Select at least one student.') }}');return}if(!form.querySelector('[name=target_class_id]').value){alert('{{ __('Choose a destination class.') }}');return}openClassSecurityModal(form,'{{ __('Transfer selected students') }}',false)}function closeClassSecurityModal(){document.getElementById('class-security-modal').classList.add('hidden');document.getElementById('class-security-modal').classList.remove('flex');sensitiveClassForm=null}function submitClassSecurityModal(){if(!sensitiveClassForm)return;let input=sensitiveClassForm.querySelector('[name=password_confirmation_action]');if(!input){input=document.createElement('input');input.type='hidden';input.name='password_confirmation_action';sensitiveClassForm.appendChild(input)}input.value=document.getElementById('class-security-password').value;sensitiveClassForm.submit()}</script>
<div id="transfer-warning-modal" class="fixed inset-0 z-[140] hidden items-center justify-center bg-black/50 p-4"><div class="w-full max-w-sm rounded-2xl bg-white p-6 text-center shadow-2xl"><div class="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-amber-100 text-2xl text-amber-700">!</div><h3 class="mt-4 text-lg font-semibold text-gray-900">{{ __('Transfer not possible') }}</h3><p id="transfer-warning-message" class="mt-2 text-sm text-gray-600"></p><button type="button" onclick="closeTransferWarning()" class="mt-6 rounded-lg bg-emerald-700 px-5 py-2 text-sm font-semibold text-white">{{ __('OK') }}</button></div></div>
<script>
let transferWarningMessage='';function showTransferWarning(message){transferWarningMessage=message;document.getElementById('transfer-warning-message').textContent=message;const modal=document.getElementById('transfer-warning-modal');modal.classList.remove('hidden');modal.classList.add('flex')}function closeTransferWarning(){const modal=document.getElementById('transfer-warning-modal');modal.classList.add('hidden');modal.classList.remove('flex')}
window.openTransferModal=function(){const form=document.getElementById('transfer-students-form');if(!form.querySelector('.student-transfer:checked')){showTransferWarning(@json(__('Select at least one student.')));return}if(!form.querySelector('[name="target_class_id"]')?.value){showTransferWarning(@json(__('Choose a destination class.')));return}openClassSecurityModal(form,@json(__('Transfer selected students')),false)};
document.addEventListener('DOMContentLoaded',()=>{const form=document.getElementById('transfer-students-form');if(!form)return;form.addEventListener('submit',event=>{if(!form.querySelector('.student-transfer:checked')){event.preventDefault();showTransferWarning(@json(__('Select at least one student.')));return}if(!form.querySelector('[name="target_class_id"]')?.value){event.preventDefault();showTransferWarning(@json(__('Choose a destination class.')))}})});
</script>
</x-app-layout>
