<x-app-layout>
<x-slot name="header"><h2 class="font-semibold text-xl">{{ __('Edit program') }}</h2></x-slot>
<div class="mx-auto max-w-2xl py-8 sm:px-6 lg:px-8"><form method="POST" action="{{ route('programs.update', $program) }}" class="space-y-3 rounded-xl bg-white p-6 shadow">@csrf @method('PUT')
@if($isAdmin)<label class="block">{{ __('Teacher') }}<select name="teacher_id" required class="mt-1 w-full rounded">@foreach($teachers as $teacher)<option value="{{ $teacher->id }}" @selected(old('teacher_id', $program->teacher_id) == $teacher->id)>{{ $teacher->localizedFunctionLabel() }}</option>@endforeach</select></label>@else<input type="hidden" name="teacher_id" value="{{ auth()->id() }}">@endif
<label class="block">{{ __('Class') }}<select name="school_class_id" required class="mt-1 w-full rounded">@foreach($classes as $class)<option value="{{ $class->id }}" @selected(old('school_class_id', $program->school_class_id) == $class->id)>{{ $class->name }}</option>@endforeach</select></label><label class="block">{{ __('Subject') }}<select name="subject_name" required class="mt-1 w-full rounded">@foreach($subjects as $subject)<option value="{{ $subject->name }}" @selected(old('subject_name', $program->subject?->name) === $subject->name)>{{ $subject->localizedName() }}</option>@endforeach</select></label><label class="block">{{ __('Program') }}<input name="title" value="{{ old('title', $program->title) }}" required class="mt-1 w-full rounded"></label><label class="block">{{ __('Period') }}<input name="period_name" value="{{ old('period_name', $program->period_name) }}" required class="mt-1 w-full rounded"></label><div class="grid grid-cols-2 gap-3"><label class="block">{{ __('Start') }}<input type="date" name="starts_on" value="{{ old('starts_on', $program->starts_on->format('Y-m-d')) }}" required class="mt-1 w-full rounded"></label><label class="block">{{ __('End') }}<input type="date" name="ends_on" value="{{ old('ends_on', $program->ends_on->format('Y-m-d')) }}" required class="mt-1 w-full rounded"></label></div><label class="block">{{ __('Objectives') }}<textarea name="objectives" class="mt-1 w-full rounded">{{ old('objectives', $program->objectives) }}</textarea></label>
<section class="rounded-xl border border-emerald-100 bg-emerald-50 p-4"><div class="flex items-center justify-between"><div><h3 class="font-semibold text-emerald-900">{{ __('Chapters and subchapters') }}</h3><p class="text-xs text-emerald-700">{{ __('This structure will be used to track progress after each class.') }}</p></div><button type="button" id="add-chapter" class="rounded bg-emerald-700 px-3 py-1.5 text-sm text-white">+ {{ __('Add') }}</button></div><div class="mt-3 space-y-2">@forelse($program->lessons->whereNull('parent_id') as $chapter)<div class="rounded bg-white px-3 py-2 text-sm"><strong>{{ __('Chapter') }} :</strong> {{ $chapter->title }} @foreach($chapter->children as $child)<div class="ml-5 mt-1 text-xs text-slate-600">↳ {{ $child->title }}</div>@endforeach</div>@empty<div class="text-sm text-slate-500">{{ __('No chapter added.') }}</div>@endforelse</div><div id="new-chapters" class="mt-3 space-y-2"></div></section>
<button class="rounded bg-emerald-700 px-4 py-2 text-white">{{ __('Save changes') }}</button></form></div>
<script>let chapterIndex=0;const parents=@json($program->lessons->whereNull('parent_id')->map(fn($lesson)=>['id'=>$lesson->id,'title'=>$lesson->title])->values()),chapterTitle=@json(__('Chapter or subchapter title')),mainChapter=@json(__('New main chapter')),optionalDescription=@json(__('Optional description'));document.getElementById('add-chapter').addEventListener('click',()=>{const i=chapterIndex++;const options=parents.map(p=>`<option value="${p.id}">${p.title}</option>`).join('');document.getElementById('new-chapters').insertAdjacentHTML('beforeend',`<div class="grid gap-2 rounded bg-white p-3 md:grid-cols-2"><input name="chapters[${i}][title]" placeholder="${chapterTitle}" class="rounded border-slate-300"><select name="chapters[${i}][parent_id]" class="rounded border-slate-300"><option value="">${mainChapter}</option>${options}</select><input name="chapters[${i}][description]" placeholder="${optionalDescription}" class="rounded border-slate-300 md:col-span-2"></div>`)});</script>
</x-app-layout>
