<x-app-layout>
    <x-slot name="header"><h2 class="font-semibold text-xl">{{ __('Teaching programs') }}</h2></x-slot>
    <div class="mx-auto max-w-7xl py-8 sm:px-6 lg:px-8"><div class="rounded-xl bg-white p-6 shadow"><div class="flex flex-wrap items-center justify-between gap-3"><p class="text-gray-600">{{ __('Programs and course progress.') }}</p><div class="flex flex-wrap items-center gap-2"><a href="{{ route('programs.schedule') }}" class="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white shadow-md transition hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2">{{ __('Schedule') }}</a><a href="{{ route('programs.create') }}" class="rounded bg-emerald-700 px-4 py-2 text-white">{{ __('Add a program') }}</a></div></div>
        @php($isAdmin = auth()->user()->can('roles.manage'))
        <div class="overflow-x-auto"><table class="mt-5 w-full text-left"><thead><tr class="border-b"><th class="p-2">{{ __('Program') }}</th><th class="p-2">{{ __('Subject / class') }}</th>@if($isAdmin)<th class="p-2">{{ __('Teacher') }}</th>@endif<th class="p-2">{{ __('Completed lessons') }}</th><th class="p-2">{{ __('Progress') }}</th><th class="p-2">{{ __('Action') }}</th></tr></thead><tbody>
            @forelse($programs as $program)<tr class="border-t"><td class="p-2">{{ $program->title }}<div class="text-xs text-gray-500">{{ $program->period_name }}</div></td><td class="p-2">{{ $program->subject?->localizedName() }}<div class="text-xs text-gray-500">{{ $program->schoolClass?->name }}</div></td>@if($isAdmin)<td class="p-2">{{ $program->teacher?->localizedFunctionLabel() }}</td>@endif<td class="p-2">{{ $program->lessons->whereNotNull('completed_at')->count() }}/{{ $program->lessons->count() }}</td><td class="p-2">{{ $program->lessons->count() ? round($program->lessons->whereNotNull('completed_at')->count() * 100 / $program->lessons->count()) : 0 }} %</td><td class="p-2"><div class="flex items-center gap-3"><a href="{{ route('programs.edit', $program) }}" class="rounded bg-amber-500 px-3 py-1.5 text-sm text-white">{{ __('Edit') }}</a><a href="{{ route('programs.follow', $program) }}" class="rounded bg-emerald-700 px-3 py-1.5 text-sm text-white">{{ __('Follow') }}</a>@if($isAdmin)<form method="POST" action="{{ route('programs.destroy', $program) }}" class="ml-auto">@csrf @method('DELETE')<button type="button" title="{{ __('Delete') }}" aria-label="{{ __('Delete') }}" onclick="openProgramDeleteModal(this.closest('form'), '{{ e($program->title) }}')" class="grid h-9 w-9 place-items-center text-red-700 transition hover:text-red-900"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="h-5 w-5"><path d="M3 6h18M9 6V4h6v2m-8 0 1 14h8l1-14M10 10v6m4-6v6"/></svg></button></form>@endif</div></td></tr>
            @empty<tr><td colspan="6" class="py-4">{{ __('No program created.') }}</td></tr>@endforelse
        </tbody></table></div>
    </div></div>
    <div id="program-delete-modal" class="fixed inset-0 z-[80] hidden items-center justify-center bg-black/40 p-4"><div class="w-full max-w-sm rounded-2xl bg-white p-6 shadow-xl"><h3 class="text-lg font-semibold text-red-700">{{ __('Delete program') }}</h3><p id="program-delete-text" class="mt-2 text-sm text-gray-600"></p><label class="mt-4 block text-sm">{{ __('Administrator password') }}<input id="program-delete-password" type="password" class="mt-1 w-full rounded border-gray-300"></label><div class="mt-5 flex justify-end gap-3"><button type="button" onclick="closeProgramDeleteModal()" class="rounded px-4 py-2">{{ __('Cancel') }}</button><button type="button" onclick="submitProgramDeleteModal()" class="rounded bg-red-700 px-4 py-2 text-white">{{ __('Delete') }}</button></div></div></div>
<script>let programDeleteForm=null;function openProgramDeleteModal(form,title){programDeleteForm=form;document.getElementById('program-delete-text').textContent='{{ __('You are about to permanently delete the program:') }} '+title;document.getElementById('program-delete-modal').classList.remove('hidden');document.getElementById('program-delete-modal').classList.add('flex');document.getElementById('program-delete-password').focus()}function closeProgramDeleteModal(){document.getElementById('program-delete-modal').classList.add('hidden');document.getElementById('program-delete-modal').classList.remove('flex');programDeleteForm=null}function submitProgramDeleteModal(){if(!programDeleteForm)return;const input=document.createElement('input');input.type='hidden';input.name='admin_password';input.value=document.getElementById('program-delete-password').value;programDeleteForm.appendChild(input);programDeleteForm.submit()}let programDataVersion=null;async function syncPrograms(){try{const response=await fetch('{{ route('programs.version') }}',{headers:{Accept:'application/json'},cache:'no-store'});if(!response.ok)return;const data=await response.json();if(!programDataVersion){programDataVersion=data.version;return}if(programDataVersion!==data.version&&!document.getElementById('program-delete-modal').classList.contains('flex')){window.applicationNavigating=true;window.location.reload()}}catch(error){}}syncPrograms();setInterval(syncPrograms,3000);</script>
</x-app-layout>
