@php
    $canViewActivityNotifications = auth()->user()->can('activity.view');
    $canDeleteActivityNotifications = auth()->user()->can('activity.delete');
    $activityNotifications = collect(); $unreadActivityIds = collect(); $unreadActivityCount = 0; $latestActivityAt = now()->toISOString();
    if ($canViewActivityNotifications) {
        $activityQuery = \Spatie\Activitylog\Models\Activity::query()->with(['causer', 'subject'])->latest();
        $activityNotifications = (clone $activityQuery)->get();
        $latestActivityAt = optional($activityNotifications->first()?->created_at)->toISOString() ?? now()->toISOString();
        $lastSeen = auth()->user()->activity_notifications_read_at;
        $readIds = auth()->user()->activity_notifications_read_ids ?? [];
        $unreadActivityIds = (clone $activityQuery)->when($lastSeen, fn ($query) => $query->where('created_at', '>', $lastSeen))->whereNotIn('id', $readIds)->pluck('id');
        $unreadActivityCount = $unreadActivityIds->count();
    }
@endphp
<nav x-data="{ open: false }" class="sticky top-0 z-40 border-b border-emerald-100/80 bg-white/90 shadow-sm backdrop-blur">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="flex h-16 justify-between"><div class="flex"><div class="flex shrink-0 items-center"><a href="{{ route('dashboard') }}" class="flex items-center gap-2"><img src="{{ asset('images/gut-logo.png') }}" alt="GUT Center" class="h-8 w-8 object-contain"><span class="text-lg font-bold tracking-tight text-emerald-800">GUT Center</span></a></div><div class="hidden space-x-8 sm:ms-10 sm:flex"><x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">{{ __('Dashboard') }}</x-nav-link>@can('students.view')<x-nav-link :href="route('students.index')" :active="request()->routeIs('students.*')">{{ __('Students') }}</x-nav-link>@endcan @can('classes.manage')<x-nav-link :href="route('classes.index')" :active="request()->routeIs('classes.*')">{{ __('Classes') }}</x-nav-link>@endcan @can('programs.view')<x-nav-link :href="route('programs.index')" :active="request()->routeIs('programs.*')">{{ __('Programs') }}</x-nav-link>@endcan</div></div>
        <div class="hidden items-center gap-2 sm:flex">
            @if($canViewActivityNotifications)<button id="activity-notification-button" type="button" onclick="openActivityModal()" title="{{ __('Activity history') }}" class="relative inline-flex h-10 w-10 items-center justify-center rounded-full text-slate-600 hover:bg-emerald-50 hover:text-emerald-700"><svg class="relative z-0 h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0 1 18 14.158V11a6 6 0 0 0-12 0v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 0 1-6 0v-1m6 0H9"/></svg><span id="activity-badge" class="{{ $unreadActivityCount ? '' : 'hidden ' }}absolute -right-1 -top-1 z-10 flex h-5 min-w-5 items-center justify-center rounded-full bg-red-600 px-1 text-[11px] font-bold text-white ring-2 ring-white">{{ $unreadActivityCount > 99 ? '99+' : $unreadActivityCount }}</span></button>@endif
            <x-dropdown align="right" width="24"><x-slot name="trigger"><button class="inline-flex items-center rounded-lg border border-gray-200 px-3 py-2 text-sm font-medium text-gray-600">{{ strtoupper(app()->getLocale()) }}<svg class="ms-1 h-4 w-4 fill-current" viewBox="0 0 20 20"><path d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"/></svg></button></x-slot><x-slot name="content"><form method="POST" action="{{ route('language.switch', 'fr') }}">@csrf<button class="w-full px-4 py-2 text-left text-sm hover:bg-gray-100">FR</button></form><form method="POST" action="{{ route('language.switch', 'en') }}">@csrf<button class="w-full px-4 py-2 text-left text-sm hover:bg-gray-100">EN</button></form></x-slot></x-dropdown>
            <span class="text-sm font-medium text-gray-700">{{ Auth::user()->name }}</span><x-dropdown align="right" width="48"><x-slot name="trigger"><button title="{{ __('Profile') }}" aria-label="{{ __('Profile') }}" class="inline-flex h-10 w-10 items-center justify-center rounded-full bg-emerald-100 text-emerald-800 shadow-sm ring-1 ring-emerald-200"><svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M12 12a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9Zm-8.25 9a8.25 8.25 0 0 1 16.5 0 .75.75 0 0 1-.75-.75H4.5a.75.75 0 0 1-.75-.75Z"/></svg></button></x-slot><x-slot name="content">@can('roles.manage')<x-dropdown-link :href="route('admin.users.index')">{{ __('Accounts') }}</x-dropdown-link>@endcan @can('expenses.view')<x-dropdown-link :href="route('expenses.index')">{{ __('Expenses') }}</x-dropdown-link>@endcan<x-dropdown-link :href="route('profile.edit')">{{ __('Profile') }}</x-dropdown-link><form method="POST" action="{{ route('logout') }}">@csrf<x-dropdown-link :href="route('logout')" onclick="event.preventDefault();this.closest('form').submit();">{{ __('Log Out') }}</x-dropdown-link></form></x-slot></x-dropdown>
        </div><div class="-me-2 flex items-center gap-1 sm:hidden">@if($canViewActivityNotifications)<button type="button" onclick="openActivityModal()" title="{{ __('Activity history') }}" class="inline-flex h-10 w-10 items-center justify-center rounded-full text-slate-600 hover:bg-emerald-50"><svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0 1 18 14.158V11a6 6 0 0 0-12 0v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 0 1-6 0v-1m6 0H9"/></svg></button>@endif<a href="{{ route('profile.edit') }}" title="{{ __('Profile') }}" class="inline-flex h-10 w-10 items-center justify-center rounded-full bg-emerald-100 text-emerald-800 ring-1 ring-emerald-200"><svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M12 12a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9Zm-8.25 9a8.25 8.25 0 0 1 16.5 0 .75.75 0 0 1-.75-.75H4.5a.75.75 0 0 1-.75-.75Z"/></svg></a><button @click="open = ! open" class="inline-flex items-center justify-center rounded-md p-2 text-gray-400"><svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24"><path :class="{'hidden': open, 'inline-flex': ! open }" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/><path :class="{'hidden': ! open, 'inline-flex': open}" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg></button></div></div></div>
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden"><div class="space-y-1 pb-3 pt-2"><x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">{{ __('Dashboard') }}</x-responsive-nav-link>@can('students.view')<x-responsive-nav-link :href="route('students.index')" :active="request()->routeIs('students.*')">{{ __('Students') }}</x-responsive-nav-link>@endcan @can('classes.manage')<x-responsive-nav-link :href="route('classes.index')" :active="request()->routeIs('classes.*')">{{ __('Classes') }}</x-responsive-nav-link>@endcan @can('programs.view')<x-responsive-nav-link :href="route('programs.index')" :active="request()->routeIs('programs.*')">{{ __('Programs') }}</x-responsive-nav-link>@endcan @can('roles.manage')<x-responsive-nav-link :href="route('admin.users.index')" :active="request()->routeIs('admin.users.*')">{{ __('Accounts') }}</x-responsive-nav-link>@endcan<x-responsive-nav-link :href="route('profile.edit')" :active="request()->routeIs('profile.*')">{{ __('Profile') }}</x-responsive-nav-link></div><div class="border-t border-gray-200 px-4 py-3"><div class="font-medium">{{ Auth::user()->name }}</div><div class="text-sm text-gray-500">{{ Auth::user()->email }}</div><div class="mt-3 flex gap-2"><form method="POST" action="{{ route('language.switch', 'fr') }}">@csrf<button class="rounded border px-3 py-1">FR</button></form><form method="POST" action="{{ route('language.switch', 'en') }}">@csrf<button class="rounded border px-3 py-1">EN</button></form><form method="POST" action="{{ route('logout') }}">@csrf<button class="rounded border border-red-200 px-3 py-1 text-red-700">{{ __('Log Out') }}</button></form></div></div></div>
</nav>
@can('payments.view')@if(!request()->routeIs('students.show'))<script>
document.addEventListener('DOMContentLoaded', () => {
    const studentsUrl = '{{ route('students.index') }}';
    const feesUrl = '{{ route('school-fees.index') }}';
    document.querySelectorAll(`a[href="${studentsUrl}"]`).forEach((studentLink) => {
        if (studentLink.parentElement?.querySelector(`a[href="${feesUrl}"]`)) return;
        const link = studentLink.cloneNode(false);
        link.href = feesUrl;
        link.textContent = '{{ __('schoolfees.title') }}';
        studentLink.insertAdjacentElement('afterend', link);
    });
});
</script>@endif @endcan
@if($canViewActivityNotifications)<div id="activity-history-modal" class="fixed inset-0 z-[90] hidden items-center justify-center bg-black/40 p-4"><div class="flex max-h-[85vh] w-full max-w-2xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><div class="flex items-center justify-between border-b border-slate-100 px-6 py-4"><div><h2 class="font-semibold text-slate-900">{{ __('Activity history') }}</h2><p class="text-sm text-slate-500">{{ __('All recorded activities') }}</p></div><button type="button" onclick="closeActivityModal()" class="rounded-lg px-3 py-2 text-slate-500 hover:bg-slate-100">{{ __('Close') }}</button></div><div id="activity-history-list" class="overflow-y-auto px-6 py-3">@forelse($activityNotifications as $activity)@php($isNew = $unreadActivityIds->contains($activity->id))<div data-activity-id="{{ $activity->id }}" class="activity-entry border-b border-slate-100 py-4 {{ $isNew ? 'is-new -mx-2 rounded-lg bg-slate-100/70 px-2' : '' }}"><div class="flex gap-3"><span class="activity-new-dot mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-red-500 {{ $isNew ? '' : 'hidden' }}"></span><div class="min-w-0"><p class="text-sm font-medium text-slate-800">{{ \App\Services\ActivityDescriptionLocalizer::localize($activity->description) }}</p><p class="mt-1 text-xs text-slate-500">{{ $activity->causer?->localizedFunctionLabel() ?: __('System') }} · {{ $activity->created_at->format('d/m/Y H:i') }}</p></div></div></div>@empty<div id="no-activity-message" class="py-12 text-center text-sm text-slate-500">{{ __('No history recorded.') }}</div>@endforelse</div><div class="border-t border-slate-100 px-6 py-4 text-right"><button type="button" onclick="closeActivityModal()" class="rounded-lg bg-slate-800 px-4 py-2 text-sm text-white">{{ __('Close') }}</button></div></div></div>
<script>
let latestActivityAt='{{ $latestActivityAt }}';
function updateActivityBadge(count){const badge=document.getElementById('activity-badge');if(!badge)return;badge.textContent=count>99?'99+':count;badge.classList.toggle('hidden',!count)}
function activityRow(activity,isNew=true){const row=document.createElement('div');row.dataset.activityId=activity.id;row.className='activity-entry border-b border-slate-100 py-4'+(isNew?' is-new -mx-2 rounded-lg bg-slate-100/70 px-2':'');row.innerHTML=`<div class="flex gap-3"><span class="activity-new-dot mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-red-500 ${isNew?'':'hidden'}"></span><div class="min-w-0"><p class="text-sm font-medium text-slate-800"></p><p class="mt-1 text-xs text-slate-500"></p></div></div>`;row.querySelector('p').textContent=activity.description;row.querySelectorAll('p')[1].textContent=activity.causer+' · '+activity.displayed_at;return row}
async function refreshActivityFeed(){try{const response=await fetch(`{{ route('activity-notifications.feed') }}?after=${encodeURIComponent(latestActivityAt)}`,{headers:{Accept:'application/json'}});if(!response.ok)return;const data=await response.json();data.activities.forEach(activity=>{if(document.querySelector(`[data-activity-id="${activity.id}"]`))return;const list=document.getElementById('activity-history-list');document.getElementById('no-activity-message')?.remove();const row=activityRow(activity,true);list.prepend(row);if(typeof bindActivityLongPress==='function')bindActivityLongPress(row);latestActivityAt=activity.created_at});updateActivityBadge(data.unread_count)}catch(error){}}
function openActivityModal(){document.getElementById('activity-history-modal').classList.remove('hidden');document.getElementById('activity-history-modal').classList.add('flex')}
function closeActivityModal(){document.getElementById('activity-history-modal').classList.add('hidden');document.getElementById('activity-history-modal').classList.remove('flex')}
@if($canDeleteActivityNotifications)
let activitySelectionMode=false,activityPressTimer=null;
function activityCheckbox(row){let box=row.querySelector('.activity-select');if(!box){box=document.createElement('input');box.type='checkbox';box.className='activity-select mt-1 h-4 w-4 rounded border-slate-300 text-emerald-700';box.addEventListener('click',event=>event.stopPropagation());row.querySelector('.flex').prepend(box)}return box}
function toggleActivitySelection(enabled=true){activitySelectionMode=enabled;document.querySelectorAll('.activity-entry').forEach(row=>{const box=activityCheckbox(row);box.classList.toggle('hidden',!enabled);if(!enabled)box.checked=false});document.getElementById('activity-selection-actions')?.classList.toggle('hidden',!enabled)}
function bindActivityLongPress(row){if(row.dataset.longPressBound)return;row.dataset.longPressBound='1';row.addEventListener('pointerdown',event=>{if(event.target.closest('input,button'))return;activityPressTimer=setTimeout(()=>{toggleActivitySelection();activityCheckbox(row).checked=true},650)});['pointerup','pointerleave','pointercancel'].forEach(name=>row.addEventListener(name,()=>clearTimeout(activityPressTimer)));row.addEventListener('contextmenu',event=>{event.preventDefault();toggleActivitySelection();activityCheckbox(row).checked=true})}
function bindAllActivityLongPress(){document.querySelectorAll('.activity-entry').forEach(bindActivityLongPress)}
async function deleteSelectedActivities(){const ids=[...document.querySelectorAll('.activity-select:checked')].map(box=>box.closest('[data-activity-id]').dataset.activityId);if(!ids.length||!await window.confirmDeletion('{{ __('Move the selected notifications to the trash?') }}'))return;const response=await fetch('{{ route('activity-notifications.destroy') }}',{method:'DELETE',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content,'Content-Type':'application/json'},body:JSON.stringify({ids})});if(!response.ok){alert('{{ __('Action not allowed.') }}');return}const result=await response.json();(result.deleted_ids||[]).forEach(id=>document.querySelector(`[data-activity-id="${id}"]`)?.remove());toggleActivitySelection(false)}
document.addEventListener('DOMContentLoaded',()=>{const footer=document.querySelector('#activity-history-modal .border-t');const actions=document.createElement('div');actions.id='activity-selection-actions';actions.className='hidden mr-3 inline-flex items-center gap-3';actions.innerHTML='<label class="text-sm text-slate-600"><input id="activity-select-all" type="checkbox" class="mr-1"> {{ __('Select all') }}</label><button type="button" class="rounded-lg bg-red-600 px-3 py-2 text-sm text-white">{{ __('Delete selected') }}</button><button type="button" class="text-sm text-slate-600">{{ __('Cancel') }}</button>';footer.prepend(actions);actions.querySelector('#activity-select-all').addEventListener('change',event=>document.querySelectorAll('.activity-select').forEach(box=>box.checked=event.target.checked));actions.querySelectorAll('button')[0].addEventListener('click',deleteSelectedActivities);actions.querySelectorAll('button')[1].addEventListener('click',()=>toggleActivitySelection(false));bindAllActivityLongPress()});
@endif
setInterval(refreshActivityFeed,5000);
</script>@endif
@if($canViewActivityNotifications)<script>document.addEventListener('DOMContentLoaded',()=>document.querySelector('#activity-history-modal .border-t button[onclick="closeActivityModal()"]')?.remove());</script>@endif
@if($canViewActivityNotifications)
<script>
const activityUrlMap=@json($activityNotifications->mapWithKeys(fn($activity)=>[$activity->id=>\App\Services\ActivityDestinationResolver::url($activity)]));
if(typeof activityRow==='function'){const originalActivityRow=activityRow;activityRow=function(activity,isNew=true){const row=originalActivityRow(activity,isNew);row.dataset.activityUrl=activity.url||activityUrlMap[activity.id]||'';row.classList.add('cursor-pointer','hover:bg-emerald-50/60');return row;};}
document.querySelectorAll('.activity-entry').forEach(row=>row.classList.add('cursor-pointer','hover:bg-emerald-50/60'));
document.addEventListener('click',async event=>{const row=event.target.closest('.activity-entry');if(!row||event.target.closest('input,button,a')||(typeof activitySelectionMode!=='undefined'&&activitySelectionMode))return; if(row.classList.contains('is-new')){await fetch('{{ route('activity-notifications.read') }}',{method:'POST',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({id:Number(row.dataset.activityId)})});row.classList.remove('is-new','-mx-2','rounded-lg','bg-slate-100/70','px-2');row.querySelector('.activity-new-dot')?.classList.add('hidden');const badge=document.getElementById('activity-badge');updateActivityBadge(Math.max(0,Number(badge?.textContent||0)-1));}const url=row.dataset.activityUrl||activityUrlMap[row.dataset.activityId];if(url)window.location.href=url;});
</script>
@endif
