<x-app-layout>
    @php($roleLabels = ['Admin' => __('Admin'), 'Prof' => __('Professor'), 'Secrétaire' => __('Secretary'), 'Trésorier' => __('Treasurer')])
    <x-slot name="header"><h2 class="font-semibold text-xl">{{ __('Create account') }}</h2></x-slot>
    <div class="mx-auto max-w-4xl py-8 sm:px-6 lg:px-8">
        <form method="POST" enctype="multipart/form-data" action="{{ route('admin.users.store') }}" class="space-y-6 rounded-xl bg-white p-6 shadow">@csrf
            <section><h3 class="mb-3 font-semibold">{{ __('Personal information') }}</h3><div class="grid gap-4 md:grid-cols-2">
                <label>{{ __('First name') }}<input name="first_name" value="{{ old('first_name') }}" required class="mt-1 block w-full rounded border-gray-300"></label>
                <label>{{ __('Last name') }}<input name="last_name" value="{{ old('last_name') }}" required class="mt-1 block w-full rounded border-gray-300"></label>
                <label>{{ __('Email') }}<input type="email" name="email" value="{{ old('email') }}" required class="mt-1 block w-full rounded border-gray-300"></label>
                <label>{{ __('Phone') }}<input name="phone" value="{{ old('phone') }}" class="mt-1 block w-full rounded border-gray-300"></label>
                <label>{{ __('CIN') }}<input name="cin" value="{{ old('cin') }}" class="mt-1 block w-full rounded border-gray-300"></label>
                <label>{{ __('Birth date') }}<input type="date" name="birth_date" value="{{ old('birth_date') }}" class="mt-1 block w-full rounded border-gray-300"></label>
                <label>{{ __('Birth place') }}<input name="birth_place" value="{{ old('birth_place') }}" class="mt-1 block w-full rounded border-gray-300"></label>
                <label>{{ __('Emergency contact') }}<input name="emergency_contact" value="{{ old('emergency_contact') }}" class="mt-1 block w-full rounded border-gray-300"></label>
            </div><label class="mt-4 block">{{ __('Address') }}<textarea name="address" class="mt-1 block w-full rounded border-gray-300">{{ old('address') }}</textarea></label><div id="account-photo-control" class="mt-4 flex flex-col items-start gap-2"><span class="text-sm font-medium">{{ __('Profile photo') }}</span><input id="account-photo" type="file" name="photo" accept="image/*" class="hidden"><button id="account-add-photo" type="button" class="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-medium text-white hover:bg-emerald-800">{{ __('Add a photo') }}</button><span id="account-photo-name" class="hidden max-w-xs truncate rounded-lg bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-700"></span></div></section>
            <section><h3 class="mb-3 font-semibold">{{ __('Account and contract') }}</h3><div class="grid gap-4 md:grid-cols-2">
                <label>{{ __('Role') }}<select id="account-role" name="role" required class="mt-1 block w-full rounded border-gray-300">@foreach($roles as $role)<option value="{{ $role }}" @selected(old('role') === $role)>{{ $roleLabels[$role] ?? __($role) }}</option>@endforeach</select></label>
                <label>{{ __('Function assigned automatically') }}<input id="account-function" readonly class="mt-1 block w-full rounded border-gray-200 bg-gray-100 text-gray-600"></label>
                <label>{{ __('Contract type') }}<select name="contract_type" class="mt-1 block w-full rounded border-gray-300"><option value="">—</option>@foreach(['CDI','CDD','Stage','Prestataire'] as $type)<option value="{{ $type }}" @selected(old('contract_type') === $type)>{{ ['Stage' => __('Internship'), 'Prestataire' => __('Service provider')][$type] ?? $type }}</option>@endforeach</select></label>
                <label>{{ __('Contract start date') }}<input type="date" name="contract_start_date" value="{{ old('contract_start_date') }}" class="mt-1 block w-full rounded border-gray-300"></label>
                <label>{{ __('Contract end date') }}<input type="date" name="contract_end_date" value="{{ old('contract_end_date') }}" class="mt-1 block w-full rounded border-gray-300"></label>
                <label>{{ __('Leave start date') }}<input type="date" name="leave_start_date" value="{{ old('leave_start_date') }}" class="mt-1 block w-full rounded border-gray-300"></label>
                <label>{{ __('Leave end date') }}<input type="date" name="leave_end_date" value="{{ old('leave_end_date') }}" class="mt-1 block w-full rounded border-gray-300"></label>
                <label>{{ __('Password') }}<input type="password" name="password" required class="mt-1 block w-full rounded border-gray-300"></label>
                <label>{{ __('Confirm Password') }}<input type="password" name="password_confirmation" required class="mt-1 block w-full rounded border-gray-300"></label>
            </div></section>
            <fieldset><legend class="font-semibold">{{ __('Additional access') }}</legend><div class="mt-2 grid gap-2 sm:grid-cols-2">@foreach($permissions as $permission)<label class="text-sm"><input type="checkbox" name="permissions[]" value="{{ $permission->name }}" @checked(in_array($permission->name, old('permissions', []), true))> {{ __(config('permissions.labels')[$permission->name] ?? $permission->name) }}</label>@endforeach</div></fieldset>
            <section id="teacher-settings" class="hidden rounded-xl border border-emerald-100 bg-emerald-50 p-4"><h3 class="font-semibold text-emerald-900">{{ __('Teaching assignments') }}</h3><p class="mt-1 text-sm text-emerald-800">{{ __('Choose the classes and enter the subjects taught by this professor.') }}</p><div class="mt-3 grid gap-2 sm:grid-cols-2">@foreach($classes as $class)<label class="text-sm"><input type="checkbox" name="teacher_class_ids[]" value="{{ $class->id }}"> {{ $class->name }}</label>@endforeach</div><label class="mt-4 block text-sm">{{ __('Subjects taught') }}<input name="teaching_subjects" value="{{ old('teaching_subjects') }}" placeholder="{{ __('For example: French, English') }}" class="mt-1 w-full rounded border-gray-300"></label></section>
            <div class="flex gap-3"><button class="rounded bg-emerald-700 px-4 py-2 text-white">{{ __('Create account') }}</button><a href="{{ route('admin.users.index') }}" class="rounded border px-4 py-2">{{ __('Cancel') }}</a></div>
        </form>
    </div>
    <script>document.addEventListener('DOMContentLoaded',()=>{const i=document.querySelector('[name=teaching_subjects]');if(!i)return;const s=document.createElement('select');s.name=i.name+'[]';s.multiple=true;s.className=i.className;s.innerHTML='<option value="">—</option>@foreach($subjects as $subject)<option value="{{ $subject->name }}">{{ $subject->name }}{{ $subject->code ? ' ('.$subject->code.')' : '' }}</option>@endforeach';i.replaceWith(s);});</script>
    <script>const accountRoleLabels=@json($roleLabels);function updateFunction(){const role=document.getElementById('account-role').value;const first=document.querySelector('[name=first_name]').value.trim();const roleLabel=accountRoleLabels[role]||role;document.getElementById('account-function').value=role==='Admin'?roleLabel:[roleLabel,first].filter(Boolean).join(' ')}function syncContractEnd(){const type=document.querySelector('[name=contract_type]');const end=document.querySelector('[name=contract_end_date]');end.closest('label').classList.toggle('hidden',type.value==='CDI');if(type.value==='CDI')end.value=''}document.getElementById('account-role').addEventListener('change',updateFunction);document.querySelector('[name=first_name]').addEventListener('input',updateFunction);document.querySelector('[name=contract_type]').addEventListener('change',syncContractEnd);const contractGrid=document.querySelector('[name=contract_type]').closest('.grid');contractGrid.insertAdjacentHTML('beforeend',`<label>{{ __('Monthly salary (Ar)') }}<input type="number" min="0" step="0.01" name="monthly_salary_amount" class="mt-1 block w-full rounded border-gray-300"></label><label>{{ __('Salary payment day') }}<input type="number" min="1" max="31" name="salary_payment_day" value="1" class="mt-1 block w-full rounded border-gray-300"></label>`);updateFunction();syncContractEnd();</script>
<div id="account-photo-choice" class="fixed inset-0 z-[160] hidden items-center justify-center bg-black/60 p-4"><div class="w-full max-w-sm rounded-2xl bg-white p-6 shadow-2xl"><div class="flex items-center justify-between"><h3 class="text-lg font-semibold">{{ __('Add a photo') }}</h3><button type="button" onclick="closeAccountPhotoChoice()" class="rounded-lg px-3 py-1 text-slate-500">{{ __('Close') }}</button></div><p class="mt-2 text-sm text-slate-600">{{ __('Choose the source of the student photo.') }}</p><div class="mt-5 grid gap-3"><button id="account-photo-camera" type="button" class="rounded-xl bg-emerald-700 px-4 py-3 font-medium text-white">{{ __('Camera') }}</button><button id="account-photo-file" type="button" class="rounded-xl border border-slate-300 px-4 py-3 font-medium text-slate-700">{{ __('Choose a file') }}</button></div></div></div>
<div id="account-camera" class="fixed inset-0 z-[170] hidden items-start justify-center overflow-y-auto bg-black/65 px-4 py-6 sm:items-center"><div class="my-auto w-full max-w-sm overflow-hidden rounded-2xl bg-white shadow-2xl"><div class="relative h-56 bg-slate-950"><button type="button" onclick="closeAccountCamera()" class="absolute right-3 top-3 z-10 rounded-full bg-black/70 px-3 py-1.5 text-xs text-white">{{ __('Close') }}</button><video id="account-video" class="h-full w-full object-cover" autoplay playsinline muted></video><img id="account-preview" class="hidden h-full w-full object-cover" alt="{{ __('Captured photo') }}"></div><div class="flex min-h-[110px] items-center justify-center gap-4 bg-white p-4"><button id="account-capture" type="button" aria-label="{{ __('Capture') }}" class="h-16 w-16 rounded-full border-4 border-emerald-100 bg-emerald-700 shadow-lg"></button><div id="account-review" class="hidden gap-3"><button type="button" onclick="retryAccountPhoto()" class="rounded-lg border border-slate-300 px-4 py-2 text-sm">{{ __('Retry') }}</button><button type="button" onclick="saveAccountPhoto()" class="rounded-lg bg-emerald-700 px-4 py-2 text-sm text-white">{{ __('Save') }}</button></div></div></div></div><canvas id="account-canvas" class="hidden"></canvas>
<script>
const accountFile=document.getElementById('account-photo'),accountName=document.getElementById('account-photo-name'),accountChoice=document.getElementById('account-photo-choice'),accountCamera=document.getElementById('account-camera'),accountVideo=document.getElementById('account-video'),accountPreview=document.getElementById('account-preview'),accountCanvas=document.getElementById('account-canvas'),accountCapture=document.getElementById('account-capture'),accountReview=document.getElementById('account-review');let accountStream=null,accountBlob=null;const showAccountName=n=>{accountName.textContent='✓ '+n;accountName.title=n;accountName.classList.remove('hidden')};accountFile.addEventListener('change',()=>{if(accountFile.files?.[0])showAccountName(accountFile.files[0].name)});document.getElementById('account-add-photo').onclick=()=>{accountChoice.classList.remove('hidden');accountChoice.classList.add('flex')};window.closeAccountPhotoChoice=()=>{accountChoice.classList.add('hidden');accountChoice.classList.remove('flex')};const stopAccount=()=>{accountStream?.getTracks().forEach(t=>t.stop());accountStream=null;accountVideo.srcObject=null};window.closeAccountCamera=()=>{stopAccount();accountCamera.classList.add('hidden');accountCamera.classList.remove('flex');accountBlob=null};const startAccount=async()=>{closeAccountPhotoChoice();try{accountStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:960},height:{ideal:720}},audio:false});accountVideo.srcObject=accountStream;accountVideo.classList.remove('hidden');accountPreview.classList.add('hidden');accountCapture.classList.remove('hidden');accountReview.classList.add('hidden');accountReview.classList.remove('flex');accountCamera.classList.remove('hidden');accountCamera.classList.add('flex')}catch(e){alert(@json(__('Allow camera access to take a photo.')))}};document.getElementById('account-photo-camera').onclick=startAccount;document.getElementById('account-photo-file').onclick=()=>{closeAccountPhotoChoice();accountFile.click()};accountCapture.onclick=()=>{if(!accountVideo.videoWidth)return;accountCanvas.width=accountVideo.videoWidth;accountCanvas.height=accountVideo.videoHeight;accountCanvas.getContext('2d').drawImage(accountVideo,0,0);accountCanvas.toBlob(b=>{accountBlob=b;accountPreview.src=URL.createObjectURL(b);accountVideo.classList.add('hidden');accountPreview.classList.remove('hidden');accountCapture.classList.add('hidden');accountReview.classList.remove('hidden');accountReview.classList.add('flex');stopAccount()},'image/jpeg',.9)};window.retryAccountPhoto=()=>{closeAccountCamera();startAccount()};window.saveAccountPhoto=()=>{if(!accountBlob)return;const f=new File([accountBlob],`photo-compte-${Date.now()}.jpg`,{type:'image/jpeg'}),d=new DataTransfer();d.items.add(f);accountFile.files=d.files;showAccountName(f.name);closeAccountCamera()};
    </script><script>document.addEventListener('DOMContentLoaded',()=>{const s=document.querySelector('select[name="teaching_subjects[]"]');if(!s)return;s.multiple=true;s.classList.add('hidden');const w=document.createElement('div');w.className='mt-1 rounded border border-gray-300 bg-white p-2';const chips=document.createElement('div');chips.className='flex flex-wrap gap-1';const menu=document.createElement('select');menu.className='mt-2 w-full rounded border-gray-200';menu.innerHTML='<option value="">Ajouter une matière…</option>'+[...s.options].filter(o=>o.value).map(o=>`<option value="${o.value}">${o.text}</option>`).join('');w.append(chips,menu);s.parentNode.insertBefore(w,s);function draw(){chips.innerHTML='';[...s.options].filter(o=>o.selected).forEach(o=>{const b=document.createElement('button');b.type='button';b.className='rounded bg-emerald-100 px-2 py-1 text-sm';b.textContent=o.text+' ×';b.onclick=()=>{o.selected=false;draw()};chips.append(b)})}menu.onchange=()=>{const o=[...s.options].find(o=>o.value===menu.value);if(o)o.selected=true;menu.value='';draw()};draw()});</script>
<script>const teacherSettings=document.getElementById('teacher-settings');function toggleTeacherSettings(){teacherSettings?.classList.toggle('hidden',document.getElementById('account-role')?.value!=='Prof')}document.getElementById('account-role')?.addEventListener('change',toggleTeacherSettings);toggleTeacherSettings();</script>
</x-app-layout>
<style>
div:has(> select[name="teaching_subjects[]"]) button { border-radius: 9999px; display: inline-flex; align-items: center; }
div:has(> select[name="teaching_subjects[]"]) button { color: #dc2626 !important; background-color: #fee2e2 !important; }
</style>
<script>document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!b.textContent.includes('×'))return;const r=b.getBoundingClientRect();if(e.clientX<r.right-24)e.stopImmediatePropagation()},true);</script>
