<x-app-layout>
    @php($roleLabels = ['Admin' => __('Admin'), 'Prof' => __('Professor'), 'Secrétaire' => __('Secretary'), 'Trésorier' => __('Treasurer')])
    <x-slot name="header"><div class="flex flex-wrap items-center justify-between gap-3"><h2 class="font-semibold text-xl">{{ __('User accounts') }}</h2><div class="flex flex-wrap gap-2"><button type="button" onclick="openAccountScannerV3()" class="inline-flex items-center rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-emerald-800">{{ __('Scan') }}</button><a href="{{ route('admin.users.create') }}" class="inline-flex items-center rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">{{ __('Create account') }}</a></div></div></x-slot>
    <div class="mx-auto max-w-7xl py-8 sm:px-6 lg:px-8">
        <div class="rounded-xl bg-white p-6 shadow">
            <div class="overflow-x-auto">
                <table class="w-full text-left">
                    <thead><tr class="border-b"><th class="p-2">{{ __('Full name') }}</th><th class="p-2">{{ __('Function') }}</th><th class="p-2">{{ __('Email') }}</th><th class="p-2">{{ __('Phone') }}</th><th class="p-2">{{ __('Role') }}</th><th class="p-2">{{ __('Leave') }}</th><th class="p-2">{{ __('Status') }}</th><th class="p-2">{{ __('Action') }}</th></tr></thead>
                    <tbody>
                        @forelse($users as $user)
                            @php($roleNames = $user->roles->pluck('name'))
                            @php($localizedRoles = $roleNames->map(fn ($role) => $roleLabels[$role] ?? __($role)))
                            @php($primaryRole = $roleNames->first())
                            @php($firstName = $user->first_name ?: explode(' ', $user->name)[0])
                            @php($functionLabel = $primaryRole ? ($primaryRole === 'Admin' ? ($roleLabels['Admin'] ?? __('Admin')) : trim(($roleLabels[$primaryRole] ?? __($primaryRole)) . ' ' . $firstName)) : __('Account'))
                            @php($leaveDays = $user->leave_start_date && $user->leave_end_date ? $user->leave_start_date->diffInDays($user->leave_end_date) + 1 : null)
                            <tr class="border-b"><td class="p-2">{{ $user->name }}</td><td class="p-2">{{ $functionLabel }}</td><td class="p-2">{{ $user->email }}</td><td class="p-2">{{ $user->phone ?: '—' }}</td><td class="p-2">{{ $localizedRoles->join(', ') ?: '—' }}</td><td class="p-2"><div class="flex flex-wrap gap-1">@if($user->leave_start_date && $user->leave_end_date)<span class="rounded-full bg-amber-100 px-2 py-1 text-xs font-medium text-amber-800">{{ $user->leave_start_date->format('d/m/Y') }} → {{ $user->leave_end_date->format('d/m/Y') }}</span><span class="rounded-full bg-sky-100 px-2 py-1 text-xs font-medium text-sky-800">{{ $leaveDays }} {{ __('days') }}</span>@else<span class="text-gray-400">—</span>@endif</div></td><td class="p-2">{{ $user->is_active ? __('Active') : __('Suspended') }}</td><td class="p-2"><a class="text-emerald-700" href="{{ route('admin.users.show', $user) }}">{{ __('View') }}</a></td></tr>
                        @empty
                            <tr><td class="p-4" colspan="8">{{ __('No result.') }}</td></tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
            <div class="mt-5">{{ $users->links() }}</div>
        </div>
    </div>
<style>#account-scan-modal>div{width:min(100%,360px);max-width:360px;min-height:390px}#account-scan-modal>div>.p-5{min-height:300px;display:flex;flex-direction:column}#account-qr-reader{width:280px;min-height:220px;max-width:100%;margin:0 auto;flex:none}#account-qr-reader video{height:220px;max-height:220px;object-fit:cover}#account-scan-status{min-height:40px}#account-scan-retry{position:relative;z-index:3;flex:none}#account-scan-retry-v2{display:none!important}#account-scan-error-modal{background-color:rgba(0,0,0,.70)!important}</style>
<script src="https://unpkg.com/html5-qrcode@2.3.8/html5-qrcode.min.js"></script>
<div id="account-scan-modal" class="fixed inset-0 z-[100000] hidden items-center justify-center bg-black/65 p-4"><div class="w-full max-w-md overflow-hidden rounded-2xl bg-white shadow-2xl"><div class="flex items-center justify-between border-b px-5 py-4"><h3 class="text-lg font-semibold">{{ __('Scan account') }}</h3><button type="button" onclick="closeAccountScanner()" class="rounded-lg px-3 py-1 text-xl text-slate-500 hover:bg-slate-100" aria-label="{{ __('Close') }}">×</button></div><div class="p-5"><div id="account-qr-reader" class="overflow-hidden rounded-xl border border-slate-200"></div><p id="account-scan-status" class="mt-3 text-center text-sm text-slate-500">{{ __('Allow camera access and present the account QR code.') }}</p><button id="account-scan-retry-v2" type="button" onclick="retryAccountScannerV2()" class="mx-auto mt-4 rounded-lg bg-sky-700 px-4 py-2 text-sm font-semibold text-white hover:bg-sky-800">{{ __('Retry') }}</button></div></div></div>
<div id="account-scan-error-modal" class="fixed inset-0 z-[100001] hidden items-center justify-center bg-black/65 p-4"><div class="w-full max-w-sm rounded-2xl bg-white p-6 text-center shadow-2xl"><h3 class="text-lg font-semibold text-slate-900">{{ __('Scan account') }}</h3><p id="account-scan-error-message" class="mt-3 text-sm text-slate-600"></p><div class="mt-6 flex justify-center gap-3"><button type="button" onclick="retryAccountScannerV3()" class="rounded-lg bg-emerald-700 px-5 py-2.5 text-sm font-semibold text-white shadow-md transition hover:bg-emerald-800 focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:ring-offset-2">{{ __('Retry') }}</button><button type="button" onclick="cancelAccountScanErrorV3()" class="rounded-lg bg-slate-200 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-300">{{ __('Cancel') }}</button></div></div></div>
<script>
let accountQrScanner=null,accountQrBusy=false;
async function openAccountScanner(){const modal=document.getElementById('account-scan-modal'),status=document.getElementById('account-scan-status');modal.classList.remove('hidden');modal.classList.add('flex');status.textContent=@json(__('Starting camera…'));if(typeof Html5Qrcode==='undefined'){status.textContent=@json(__('QR reader unavailable. Check the internet connection.'));return}if(accountQrScanner)return;accountQrBusy=false;accountQrScanner=new Html5Qrcode('account-qr-reader');try{await accountQrScanner.start({facingMode:'environment'},{fps:10,qrbox:{width:220,height:220}},async(value)=>{if(accountQrBusy)return;accountQrBusy=true;status.textContent=@json(__('Account found, opening the details…'));try{await accountQrScanner.stop()}catch(e){}try{accountQrScanner.clear()}catch(e){}accountQrScanner=null;const response=await fetch('{{ route('admin.users.scan') }}?value='+encodeURIComponent(value),{headers:{Accept:'application/json'}});const data=await response.json().catch(()=>({}));if(!response.ok||!data.url){accountQrBusy=false;status.textContent=data.message||@json(__('No account found.'));return}window.location.href=data.url},()=>{})}catch(error){status.textContent=@json(__('Unable to access the camera.'));accountQrScanner=null}}
async function closeAccountScanner(){if(accountQrScanner){try{await accountQrScanner.stop()}catch(e){}try{accountQrScanner.clear()}catch(e){}accountQrScanner=null}const modal=document.getElementById('account-scan-modal');modal.classList.add('hidden');modal.classList.remove('flex')}
</script>
<script>
// Enhanced scanner state: display a retry action when a QR code is unknown or the camera fails.
function accountRetryButton(){let button=document.getElementById('account-scan-retry');if(!button){button=document.createElement('button');button.id='account-scan-retry';button.type='button';button.textContent=@json(__('Retry'));button.className='mx-auto mt-4 hidden rounded-lg bg-sky-700 px-4 py-2 text-sm font-semibold text-white hover:bg-sky-800';document.getElementById('account-scan-status')?.after(button)}button.onclick=retryAccountScanner;return button}
document.addEventListener('DOMContentLoaded',accountRetryButton);
async function stopAccountScanner(){if(accountQrScanner){try{await accountQrScanner.stop()}catch(e){}try{accountQrScanner.clear()}catch(e){}accountQrScanner=null}}
async function startAccountScanner(){const status=document.getElementById('account-scan-status'),retry=accountRetryButton();retry.classList.add('hidden');status.textContent=@json(__('Starting camera…'));if(typeof Html5Qrcode==='undefined'){status.textContent=@json(__('QR reader unavailable. Check the internet connection.'));retry.classList.remove('hidden');return}accountQrBusy=false;accountQrScanner=new Html5Qrcode('account-qr-reader');try{await accountQrScanner.start({facingMode:'environment'},{fps:10,qrbox:{width:220,height:220}},async(value)=>{if(accountQrBusy)return;accountQrBusy=true;status.textContent=@json(__('Account found, opening the details…'));await stopAccountScanner();const response=await fetch('{{ route('admin.users.scan') }}?value='+encodeURIComponent(value),{headers:{Accept:'application/json'}});const data=await response.json().catch(()=>({}));if(!response.ok||!data.url){accountQrBusy=false;status.textContent=data.message||@json(__('No account found.'));retry.classList.remove('hidden');return}window.location.href=data.url},()=>{})}catch(error){await stopAccountScanner();status.textContent=@json(__('Unable to access the camera.'));retry.classList.remove('hidden')}}
async function openAccountScanner(){const modal=document.getElementById('account-scan-modal');modal.classList.remove('hidden');modal.classList.add('flex');if(!accountQrScanner)await startAccountScanner()}
async function retryAccountScanner(){await stopAccountScanner();await startAccountScanner()}
async function closeAccountScanner(){await stopAccountScanner();const modal=document.getElementById('account-scan-modal');modal.classList.add('hidden');modal.classList.remove('flex')}
</script>
<script>
let accountQrScannerV2=null,accountQrBusyV2=false;
function accountRetryButtonV2(){let button=document.getElementById('account-scan-retry-v2');if(!button){button=document.createElement('button');button.id='account-scan-retry-v2';button.type='button';button.textContent=@json(__('Retry'));button.className='mx-auto mt-4 rounded-lg bg-sky-700 px-4 py-2 text-sm font-semibold text-white hover:bg-sky-800';const status=document.getElementById('account-scan-status');status?.parentElement?.appendChild(button)}button.onclick=retryAccountScannerV2;return button}
async function stopAccountScannerV2(){if(accountQrScannerV2){try{await accountQrScannerV2.stop()}catch(e){}try{accountQrScannerV2.clear()}catch(e){}accountQrScannerV2=null}}
async function startAccountScannerV2(){const status=document.getElementById('account-scan-status'),retry=accountRetryButtonV2();status.textContent='Initialisation de la caméra…';if(typeof Html5Qrcode==='undefined'){status.textContent='Lecteur QR indisponible.';return}accountQrBusyV2=false;accountQrScannerV2=new Html5Qrcode('account-qr-reader');try{await accountQrScannerV2.start({facingMode:'environment'},{fps:10,qrbox:{width:220,height:220}},async(value)=>{if(accountQrBusyV2)return;accountQrBusyV2=true;status.textContent='Vérification du compte…';await stopAccountScannerV2();const response=await fetch('{{ route('admin.users.scan') }}?value='+encodeURIComponent(value),{headers:{Accept:'application/json'}});const data=await response.json().catch(()=>({}));if(!response.ok||!data.url){accountQrBusyV2=false;status.textContent=data.message||'Aucun compte correspondant.';return}window.location.href=data.url},()=>{})}catch(error){await stopAccountScannerV2();status.textContent='Impossible d’accéder à la caméra.'}}
async function openAccountScannerV2(){const modal=document.getElementById('account-scan-modal');modal.classList.remove('hidden');modal.classList.add('flex');await startAccountScannerV2()}
async function retryAccountScannerV2(){await stopAccountScannerV2();await startAccountScannerV2()}
</script>
<script>
let accountQrScannerV3=null,accountQrBusyV3=false;
function showAccountScanErrorV3(message){const camera=document.getElementById('account-scan-modal');camera.classList.add('hidden');camera.classList.remove('flex');const error=document.getElementById('account-scan-error-modal');document.getElementById('account-scan-error-message').textContent=message;error.classList.remove('hidden');error.classList.add('flex')}
function cancelAccountScanErrorV3(){const error=document.getElementById('account-scan-error-modal');error.classList.add('hidden');error.classList.remove('flex')}
async function stopAccountScannerV3(){if(accountQrScannerV3){try{await accountQrScannerV3.stop()}catch(e){}try{accountQrScannerV3.clear()}catch(e){}accountQrScannerV3=null}}
async function startAccountScannerV3(){const modal=document.getElementById('account-scan-modal'),status=document.getElementById('account-scan-status');const error=document.getElementById('account-scan-error-modal');error.classList.add('hidden');error.classList.remove('flex');modal.classList.remove('hidden');modal.classList.add('flex');status.textContent=@json(__('Starting camera…'));if(typeof Html5Qrcode==='undefined'){showAccountScanErrorV3(@json(__('QR reader unavailable. Check the internet connection.')));return}accountQrBusyV3=false;accountQrScannerV3=new Html5Qrcode('account-qr-reader');try{await accountQrScannerV3.start({facingMode:'environment'},{fps:10,qrbox:{width:220,height:220}},async(value)=>{if(accountQrBusyV3)return;accountQrBusyV3=true;status.textContent=@json(__('Account found, opening the details…'));await stopAccountScannerV3();const response=await fetch('{{ route('admin.users.scan') }}?value='+encodeURIComponent(value),{headers:{Accept:'application/json'}});const data=await response.json().catch(()=>({}));if(!response.ok||!data.url){accountQrBusyV3=false;showAccountScanErrorV3(data.message||@json(__('No account found.')));return}window.location.href=data.url},()=>{})}catch(error){await stopAccountScannerV3();showAccountScanErrorV3(@json(__('Unable to access the camera.')))}}
async function openAccountScannerV3(){await startAccountScannerV3()}
async function retryAccountScannerV3(){cancelAccountScanErrorV3();await startAccountScannerV3()}
async function closeAccountScanner(){await stopAccountScannerV3();const modal=document.getElementById('account-scan-modal');modal.classList.add('hidden');modal.classList.remove('flex')}
</script>
</x-app-layout>
