<!doctype html>
<html lang="{{ app()->getLocale() }}"><head><meta charset="utf-8"><style>
@page{margin:8mm 5mm}body{width:330px;margin:0 auto;font-family:DejaVu Sans,sans-serif;font-size:11px;color:#152018}.center{text-align:center}.line{border-top:1px dashed #526257;margin:10px 0}.row{margin:6px 0}.amount{font-size:18px;font-weight:bold;text-align:center;margin:13px 0;color:#166534}.small{font-size:9px;color:#526257}
</style></head><body>
@php($roleLabels = ['Admin' => __('Admin'), 'Prof' => __('Professor'), 'Secrétaire' => __('Secretary'), 'Trésorier' => __('Treasurer')])
@php($primaryRole = $user->getRoleNames()->first())
@php($firstName = $user->first_name ?: explode(' ', $user->name)[0])
@php($functionLabel = $primaryRole ? ($primaryRole === 'Admin' ? ($roleLabels['Admin'] ?? __('Admin')) : trim(($roleLabels[$primaryRole] ?? __($primaryRole)) . ' ' . $firstName)) : '—')
<div class="center"><strong style="font-size:16px">GUT Center</strong><br><span class="small">{{ mb_strtoupper(__('Salary payment receipt')) }}</span></div>
<div class="line"></div>
<div class="row"><strong>{{ __('Reference') }} :</strong> {{ $payment->reference }}</div>
<div class="row"><strong>{{ __('Payment date') }} :</strong> {{ $payment->paid_at?->format('d/m/Y H:i') }}</div>
<div class="row"><strong>{{ __('Employee') }} :</strong> {{ $user->name }}</div>
<div class="row"><strong>{{ __('Function') }} :</strong> {{ $functionLabel }}</div>
<div class="row"><strong>{{ __('Period') }} :</strong> {{ $payment->due_date?->locale(app()->getLocale())->translatedFormat('F Y') }}</div>
<div class="row"><strong>{{ __('Due date') }} :</strong> {{ $payment->due_date?->format('d/m/Y') }}</div>
<div class="line"></div>
<div class="amount">{{ number_format((float) $payment->amount, 0, ',', ' ') }} Ar</div>
<div class="row"><strong>{{ __('Payment mode') }} :</strong> {{ ['cash'=>__('Cash'),'mobile_money'=>__('Mobile Money'),'bank_transfer'=>__('Bank transfer')][$payment->payment_method] ?? '—' }}</div>
@if($payment->payment_method === 'mobile_money')
<div class="row"><strong>{{ __('Number') }} :</strong> {{ $payment->payment_phone }}</div>
<div class="row"><strong>{{ __('Transaction ID') }} :</strong> {{ $payment->transaction_id }}</div>
@elseif($payment->payment_method === 'bank_transfer')
<div class="row"><strong>{{ __('Bank details') }} :</strong> {{ $payment->bank_details }}</div>
<div class="row"><strong>{{ __('Transaction ID') }} :</strong> {{ $payment->transaction_id }}</div>
@endif
<div class="line"></div>
<div class="center"><strong>{{ mb_strtoupper(__('Paid')) }}</strong><br><span class="small">{{ __('Recorded by') }} : {{ $payment->recordedBy?->name ?? '—' }}</span></div>
<div class="line"></div><div class="center small">{{ __('Document generated by GUT Center') }}</div>
</body></html>
